name: gdn_health
version: 1.0.0+1
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'
dependencies: 
  cupertino_icons: ^1.0.2
  flutter_bloc: any
  get_it: any
  equatable: any
  http: any
  dartz: any
  rounded_loading_button: any
  connectivity_plus: any
  cached_network_image: any
  tab_indicator_styler: any
  mockito: ^5.3.2
  bloc_test: ^9.1.0
  dcli: any
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_lints: ^2.0.0
  build_runner: any
  flutter_test: 
    sdk: flutter
flutter: 
  assets: 
    - assets/icons/
    - assets/fake_data/
  uses-material-design: true
